# -*- coding: utf-8 -*-
"""classWork_Juliette.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGftrdSIh2aNOqvP6ElfaHHK9z8D79Ie
"""

name_list = ["Kagetera", "John", "Peter", "Alex", "Claude"]

name_list.sort()

name_list.append("Juliette")
name_list.append("University")
name_list.append("Kangabe")

print(name_list)
=================================

F_lists = {"Apple": 1000, "Banana": 500, "Mango": 1200}

total_cost = 0
for fruit, price in F_lists.items():
    print(f"{fruit}: {price} RWF per kg")
    total_cost += price * 2

print(f"Total cost for 2kg of each fruit: {total_cost} RWF")

